### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by kolbma** [r-murphy/openui5-types#2]
I'm little bit confused about the usage...

Should it be possible to use tsc compiled es5 JS in the browser with openui5?  
Or do I need to use a 2nd compiler step with your __babel-plugin-transform-modules-ui5__?

It would be fine to clarify this in your readme.

**Comment by r-murphy** [comment]
@kolbma That's a very good idea. 

The best way to take advantage of typescript will require a 2nd compiler or maybe a runtime library with decorators (although I've never tried that).

I've only used the babel approach myself because I've been using that babel approach on javascript files before I started using typescript.

You _might_ be able to just use `sap.ui.define` and `SAPClass.extend()` with these types and then not require a 2nd compiler or runtime plugin, but I also haven't tried that. You've have to cast all of the modules before using them, which wouldn't be ideal. 

I'll update the readme with more details.
